#include "ProjectGenerator.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>

namespace fs = std::filesystem;

bool ProjectGenerator::createProject(const std::string& name)
{
    std::string projectPath = name;

    // Check if project already exists
    if (fs::exists(projectPath))
    {
        std::cerr << "Error: Directory '" << name << "' already exists.\n";
        return false;
    }

    try
    {
        createDirectoryStructure(projectPath);

        generateReadme(projectPath, name);
        generateToml(projectPath, name);
        generateMainC(projectPath);
        generateCMakeLists(projectPath);
        generateStartupC(projectPath);
        generateLinkerScript(projectPath);

        std::cout << "Project '" << name << "' created successfully.\n";
        return true;
    }
    catch (const std::exception& e)
    {
        std::cerr << e.what() << '\n';
        return false;
    }
}

void ProjectGenerator::createDirectoryStructure(const std::string& projectPath)
{
    fs::create_directories(projectPath + "/src");
    fs::create_directories(projectPath + "/include");
    fs::create_directories(projectPath + "/build");
}

void ProjectGenerator::generateReadme(const std::string& projectPath,
                                      const std::string& name)
{
    std::ofstream file(projectPath + "/README.md");

    if (!file)
        throw std::runtime_error("Failed to create README.md");

    file << "# " << name << "\n\n";
    file << "Generated by UnixTron\n\n";

    file << "## Commands\n\n";

    file << "```bash\n";
    file << "ut build\n";
    file << "ut flash\n";
    file << "ut run\n";
    file << "```\n";
}

void ProjectGenerator::generateToml(const std::string& projectPath,
                                    const std::string& name)
{
    std::ofstream file(projectPath + "/unixtron.toml");

    if (!file)
        throw std::runtime_error("Failed to create unixtron.toml");

    file << "name = \"" << name << "\"\n";
    file << "board = \"stm32f401cc\"\n";
    file << "toolchain = \"arm-none-eabi-gcc\"\n";
    file << "flasher = \"stlink\"\n";
    file << "optimization = \"Debug\"\n";
}

void ProjectGenerator::generateMainC(const std::string& projectPath)
{
    std::ofstream file(projectPath + "/src/main.c");

    if (!file)
        throw std::runtime_error("Failed to create src/main.c");

    file << "#include <stdint.h>\n\n";

    file << "int main(void)\n";
    file << "{\n";
    file << "    while (1)\n";
    file << "    {\n";
    file << "    }\n";
    file << "}\n";
}

void ProjectGenerator::generateCMakeLists(const std::string& projectPath)
{
    std::ofstream file(projectPath + "/CMakeLists.txt");

    if (!file)
        throw std::runtime_error("Failed to create CMakeLists.txt");

    file << "cmake_minimum_required(VERSION 3.20)\n";
    file << "project(UnixTronProject C ASM)\n\n";
    file << "# Generated by UnixTron\n";
}

void ProjectGenerator::generateStartupC(const std::string& projectPath)
{
    std::ofstream file(projectPath + "/src/startup.c");

    if (!file)
        throw std::runtime_error("Failed to create src/startup.c");

    file << R"(#include <stdint.h>

    extern int main(void);

    extern unsigned long _estack;
    extern unsigned long _sidata;
    extern unsigned long _sdata;
    extern unsigned long _edata;
    extern unsigned long _sbss;
    extern unsigned long _ebss;

    void Reset_Handler(void);
    void Default_Handler(void);

    void NMI_Handler(void)
        __attribute__((weak, alias("Default_Handler")));

    void HardFault_Handler(void)
        __attribute__((weak, alias("Default_Handler")));

    __attribute__((section(".isr_vector")))
    const void* vector_table[] =
    {
        &_estack,
        Reset_Handler,
        NMI_Handler,
        HardFault_Handler
    };

    void Reset_Handler(void)
    {
        unsigned long* src = &_sidata;
        unsigned long* dst = &_sdata;

        while (dst < &_edata)
    {
        *dst++ = *src++;
    }

        dst = &_sbss;

        while (dst < &_ebss)
    {
        *dst++ = 0;
    }

        main();

        while (1)
        {
        }
    }

    void Default_Handler(void)
    {
        while (1)
        {
        }
    }
)";
}

void ProjectGenerator::generateLinkerScript(const std::string& projectPath)
{
    std::ofstream file(projectPath + "/src/Linker.ld");
    if (!file)
        throw std::runtime_error("Failed to create src/Linker.c");

    file << R"(ENTRY(Reset_Handler)

MEMORY
{
    FLASH (rx)  : ORIGIN = 0x08000000, LENGTH = 256K
    RAM   (rwx) : ORIGIN = 0x20000000, LENGTH = 64K
}

/* Top of RAM — used as the initial stack pointer */
_estack = ORIGIN(RAM) + LENGTH(RAM);

SECTIONS
{
    /*
     * Interrupt Vector Table
     * Must be at the beginning of Flash.
     */
    .isr_vector :
    {
        . = ALIGN(4);
        KEEP(*(.isr_vector))
        . = ALIGN(4);
    } > FLASH


    /*
     * Program code + read-only data
     */
    .text :
    {
        . = ALIGN(4);

        *(.text)
        *(.text*)
        *(.rodata)
        *(.rodata*)

        . = ALIGN(4);

        _etext = .;
    } > FLASH


    /*
     * Initialized variables.
     *
     * Runtime location: RAM
     * Initial values:    stored in Flash
     */
    .data :
    {
        . = ALIGN(4);

        _sdata = .;

        *(.data)
        *(.data*)

        . = ALIGN(4);

        _edata = .;
    } > RAM AT > FLASH


    /*
     * Address in FLASH containing
     * the initial values for .data.
     */
    _sidata = LOADADDR(.data);


    /*
     * Zero-initialized variables.
     *
     * startup.c clears this region before main().
     */
    .bss :
    {
        . = ALIGN(4);

        _sbss = .;

        *(.bss)
        *(.bss*)
        *(COMMON)

        . = ALIGN(4);

        _ebss = .;
    } > RAM


    /*
     * Discard things we don't need for
     * this minimal bare-metal firmware.
     */
    /DISCARD/ :
    {
        *(.comment)
        *(.note*)
    }
}
)";
}